<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TreeLayoutStack\Factory\TemplatingServiceFactory' => __DIR__ . '/src/TreeLayoutStack/Factory/TemplatingServiceFactory.php',
    'TreeLayoutStack\Template\Template'                => __DIR__ . '/src/TreeLayoutStack/Template/Template.php',
    'TreeLayoutStack\Template\TemplateConfiguration'   => __DIR__ . '/src/TreeLayoutStack/Template/TemplateConfiguration.php',
    'TreeLayoutStack\TemplatingConfiguration'          => __DIR__ . '/src/TreeLayoutStack/TemplatingConfiguration.php',
    'TreeLayoutStack\TemplatingService'                => __DIR__ . '/src/TreeLayoutStack/TemplatingService.php',
);